### ISSUE TITLE
https://www.adminer.org/latest.php is down

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/ansible-role-adminer#15]
> TASK [geerlingguy.adminer : Download Adminer to configured directory.] *********
fatal: [nidcr]: FAILED! => {"changed": false, "dest": "/opt/adminer/index.php", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://www.adminer.org/latest.php"}

Currently the url to download the latest version is down or permanently removed (?). I couldn't find any more information on this.

We could at least provide a variable for the url so that downstream projects could solve it if it's temporary.

**Comment by geerlingguy** [comment]
Dang...

**Comment by geerlingguy** [comment]
Just added a commit to set the URL to a variable.

**Comment by geerlingguy** [comment]
And put tag 1.3.1 with just this variable change.

**Comment by oxyc** [comment]
Here's a previous bug report about it https://sourceforge.net/p/adminer/bugs-and-features/803/. Let's see what they answer

**Comment by geerlingguy** [comment]
@oxyc - Thanks, didn't realize it was actually on Sourceforge, I just looked at GitHub :P — I also sent an email to the author, not expecting a quick reply, but we'll see.

**Comment by oxyc** [comment]
It's back online! :)
